language: node_js
node_js:
    - "8.9.4"
script:
    - "npm install -g pxt"
    - "pxt target adafruit"
    - "pxt install"
    - "pxt build"
    - "rm -f -r pxt_modules"
    - "pxt target microbit"
    - "pxt install"
    - "pxt build"
sudo: false
cache:
    directories:
    - npm_modules
